name: flutter_widgets
description: Gezi Rehberi.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  splash_screen_view: ^3.0.0
  font_awesome_flutter: ^9.0.2
  salomon_bottom_bar: ^3.2.0
  email_validator:
  image_picker: ^0.7.4
  animated_theme_switcher: ^2.0.1-nullsafety.0
  theme_provider: ^0.5.0
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  curved_navigation_bar: ^1.0.3
  wiredash: ^0.7.0+1


  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - assets/konum.png
    - assets/gizlilk.txt
